# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.task_response_arr_generator:
        class: AppBundle\Service\TaskResponseArrGenerator
        arguments: ["@router"]

    app.task_group_response_arr_generator:
        class: AppBundle\Service\TaskGroupResponseArrGenerator
        arguments: ["@router", "@app.task_response_arr_generator"]