php:
    container_name: todo-php
    build: php
    volumes:
        - ./app:/app
        - ./app/var/cache:/app/var/cache
        - /tmp
    links:
        - mysql
nginx:
  container_name: todo-nginx
  build: nginx
  volumes:
      - ./app:/app
  links:
      - php
  environment:
    VIRTUAL_HOST: todo.local
  ports:
    - "3000:80"

mysql:
    build: mysql
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
     - "52000:3306"
    volumes:
      - ./db:/var/lib/mysql
