php:
    container_name: todo-php
    build: php
    working_dir: /app
    volumes:
        - ../api:/app
        - ./php/php.ini:/usr/local/etc/php/php.ini
        - ./php/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
        - ./php/pool.conf:/etc/php5/fpm/pool.d/symfony.pool.conf
    working_dir: /app
    links:
        - db
    command: php -S 0.0.0.0:8000 web/app_dev.php

angular-2:
    container_name: todo-angular-2
    image: hensansi/angular2
    volumes:
        - ../web:/app
    working_dir: /app
    command: bash -c "npm install && npm start"

db:
    container_name: todo-db
    image: mysql
    ports:
        - 52000:3306
    environment:
        MYSQL_DATABASE: symfony
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: pass
    volumes:
        - ./db:/var/lib/mysql

proxy:
    container_name: todo-proxy
    image: nginx
    ports:
        - 8000:80
        - 3000:3000
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    links:
        - angular-2
        - php

composer:
    container_name: todo-composer
    image: composer
    volumes:
        - ../api:/app
    command: bash -c "composer install && composer update"
