php:
    container_name: todo-php
    build: php-fpm
    volumes:
        - ../api:/app
        - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
        - ./php-fpm/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
        - ./php-fpm/symfony.pool.conf:/etc/php5/fpm/pool.d/symfony.pool.conf
    working_dir: /app
    links:
        - db
    command: php -S 0.0.0.0:8000 -t web

angular-2:
    container_name: todo-angular-2
    image: hensansi/angular2
    volumes:
        - ../web:/app
    working_dir: /app
    command: npm start

db:
    container_name: todo-db
    image: mysql
    ports:
        - 52000:3306
    environment:
        MYSQL_DATABASE: symfony
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: pass
    volumes:
        - ./db:/var/lib/mysql

proxy:
    container_name: todo-proxy
    image: nginx
    ports:
        - 80:80
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
    links:
        - angular-2
        - php

composer:
    container_name: todo-composer
    image: composer
    volumes:
        - ../api:/app
    command: bash -c "composer install && composer update"

npm:
    container_name: todo-npm
    image: node:alpine
    volumes:
        - ../web:/app
    working_dir: /app
    command: npm install
