# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
         our_db_provider:
             entity:
                 class: AppBundle:User
                 property: username

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_USER: IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMIN: ROLE_MODERATOR

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            #http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
            pattern: ^/

            provider: our_db_provider

            form_login:
                login_path: /api
                check_path: /api/login

            logout:
                path: /api/logout
                target: /

        login_firewall:
            pattern:   ^/api/login$
            anonymous: ~
        secured_area:
            pattern:    ^/
            form_login: ~
