security:
    providers:
        api_key_user_provider:
            id: app.security.api_key_user_provider

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_USER: IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMIN: ROLE_MODERATOR

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        authenticate:
            pattern: ^/api/authenticate
            security: false

        main:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: app.security.api_key_authenticator
            provider: api_key_user_provider

    access_control:
        - { path: ^/api, roles: ROLE_API }