# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.amazing_route_generator:
        class: AppBundle\Service\AmazingRouteGenerator
        parent: router

    app.task_response_arr_generator:
        class: AppBundle\Service\TaskResponseArrGenerator
        arguments: ["@app.amazing_route_generator"]

    app.task_group_response_arr_generator:
        class: AppBundle\Service\TaskGroupResponseArrGenerator
        arguments: ["@app.amazing_route_generator", "@app.task_response_arr_generator"]

    app.authorization.success.handler:
        class: AppBundle\Component\Authentication\Handler\LoginSuccessHandler
        arguments: ["@app.amazing_route_generator", "@security.authorization_checker"]
    app.logout.success.handler:
        class: AppBundle\Component\Authentication\Handler\LogoutSuccessHandler
        arguments: ["@app.amazing_route_generator"]

    app.entry_point:
        class: AppBundle\Component\Authentication\EntryPoint\EntryPointRedirection
        arguments: ["@app.amazing_route_generator"]